<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="13.1.0" />
        <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.21"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Service.FullTextSearch.Application\Service.FullTextSearch.Application.csproj" />
      <ProjectReference Include="..\Service.FullTextSearch.Infrastructure\Service.FullTextSearch.Infrastructure.csproj" />
    </ItemGroup>

</Project>
